<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-ana-tere-raygoza/blob/main/Ago11-12/trabajoSabado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hola mundo')

In [ ]:
lista1 = [2, '2','dos',2.0]
lista2 = ['4', 'cuatro']

In [ ]:
del lista1[2]

In [ ]:
lista1

[2, '2', 2.0]

In [ ]:
lista1.insert(2,'tres')

In [ ]:
lista1

[2, '2', 'tres', 2.0]

In [ ]:
lista3 = [lista1 , lista2]
lista3


[[2, '2', 'tres', 2.0], ['4', 'cuatro']]

In [ ]:
for i in lista1:
  print(i)

2
2
tres
2.0


In [ ]:
for i, item in enumerate(lista1):
  print(i,item)

0 2
1 2
2 tres
3 2.0


In [ ]:
type(lista1)

list

In [ ]:
import array as arr

In [ ]:
arreglo = arr.array('i',[1,2,3])
arreglo

array('i', [1, 2, 3])

In [ ]:
arreglo1 = arr.array('f',[1,2,3])
2*arreglo1

array('f', [1.0, 2.0, 3.0, 1.0, 2.0, 3.0])

In [ ]:
import numpy as np

In [ ]:
nparray1 = np.array([1,2,3])
nparray1

array([1, 2, 3])

In [ ]:
type(nparray1)

numpy.ndarray

In [ ]:
2*nparray1

array([2, 4, 6])

In [ ]:
nparray2 = np.array([1,2,3])

In [ ]:
nparray2*nparray1

array([1, 4, 9])

In [ ]:
np.dot(nparray1,nparray2)

14

In [ ]:
nparray1/nparray2

array([1., 1., 1.])